### ISSUE TITLE
ProxyError: Address already in use, trying execute rails server

### ISSUE THREAD

**Issue by martinGerez** [planetscale/planetscale-ruby#39]
Hi,

I'm trying to configure PlanetScale with Rails v6.1, using Ruby 2.7.2.

I followed the docs at [Official Doc](https://docs.planetscale.com/tutorial/connect-rails-app/#configure-rails-and-planetscale), but when I try to run `rails server` always return a ProxyError, with the following message:

```
error net.Listen: listen tcp 127.0.0.1:3305: bind: address already in use (PlanetScale::Proxy::ProxyError)
```

My database config file is:
```yaml
# config/database.yml
default: &default
  adapter: mysql2
  username: root
  host: 127.0.0.1
  port: 3305

development:
  <<: *default
  database: mydatabasename
```

my PlanetScale initializer is:
```ruby
# config/planetscale.rb

PlanetScale.start(cfg_file: '.pscale.yml')
```

dependencies versions:
```ruby
planetscale 0.2.1
mysql2 0.5.3
```

I already tried with: `spring stop` and `DISABLE_SPRING=true` becuase I read in the docs that Spring could throw this error.

Thanks in advance
